
package cidc.bizagi.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EntityManagerSOAImpl", targetNamespace = "http://SOA.BizAgi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntityManagerSOAImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntitiesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetEntitiesAsString")
    @ResponseWrapper(localName = "getEntitiesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetEntitiesAsStringResponse")
    public String getEntitiesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntitiesUsingSchemaAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetEntitiesUsingSchemaAsString")
    @ResponseWrapper(localName = "getEntitiesUsingSchemaAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetEntitiesUsingSchemaAsStringResponse")
    public String getEntitiesUsingSchemaAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveEntityAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SaveEntityAsString")
    @ResponseWrapper(localName = "saveEntityAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SaveEntityAsStringResponse")
    public String saveEntityAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntitySchemaStr", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetEntitySchemaStr")
    @ResponseWrapper(localName = "getEntitySchemaStrResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetEntitySchemaStrResponse")
    public String getEntitySchemaStr(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCaseDataUsingXPaths", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingXPaths")
    @ResponseWrapper(localName = "getCaseDataUsingXPathsResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingXPathsResponse")
    public String getCaseDataUsingXPaths(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCaseDataUsingSchemaLite", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingSchemaLite")
    @ResponseWrapper(localName = "getCaseDataUsingSchemaLiteResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingSchemaLiteResponse")
    public String getCaseDataUsingSchemaLite(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCaseDataUsingSchemaLiteAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingSchemaLiteAsString")
    @ResponseWrapper(localName = "getCaseDataUsingSchemaLiteAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingSchemaLiteAsStringResponse")
    public String getCaseDataUsingSchemaLiteAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCaseDataUsingSchema", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingSchema")
    @ResponseWrapper(localName = "getCaseDataUsingSchemaResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingSchemaResponse")
    public String getCaseDataUsingSchema(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCaseDataUsingSchemaAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingSchemaAsString")
    @ResponseWrapper(localName = "getCaseDataUsingSchemaAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingSchemaAsStringResponse")
    public String getCaseDataUsingSchemaAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCaseDataUsingXPathsAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingXPathsAsString")
    @ResponseWrapper(localName = "getCaseDataUsingXPathsAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCaseDataUsingXPathsAsStringResponse")
    public String getCaseDataUsingXPathsAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveEntityWithKeyAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SaveEntityWithKeyAsString")
    @ResponseWrapper(localName = "saveEntityWithKeyAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SaveEntityWithKeyAsStringResponse")
    public String saveEntityWithKeyAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
