
package cidc.bizagi.soa;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EntityManagerSOAImplService", targetNamespace = "http://SOA.BizAgi/", wsdlLocation = "http://200.69.103.26:7001/BizAgi-war/WebServices/EntityManagerSOA?wsdl")
public class EntityManagerSOAImplService
    extends Service
{

    private final static URL ENTITYMANAGERSOAIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cidc.bizagi.soa.EntityManagerSOAImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cidc.bizagi.soa.EntityManagerSOAImplService.class.getResource(".");
            url = new URL(baseUrl, "http://200.69.103.26:7001/BizAgi-war/WebServices/EntityManagerSOA?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://200.69.103.26:7001/BizAgi-war/WebServices/EntityManagerSOA?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ENTITYMANAGERSOAIMPLSERVICE_WSDL_LOCATION = url;
    }

    public EntityManagerSOAImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntityManagerSOAImplService() {
        super(ENTITYMANAGERSOAIMPLSERVICE_WSDL_LOCATION, new QName("http://SOA.BizAgi/", "EntityManagerSOAImplService"));
    }

    /**
     * 
     * @return
     *     returns EntityManagerSOAImpl
     */
    @WebEndpoint(name = "EntityManagerSOAImplPort")
    public EntityManagerSOAImpl getEntityManagerSOAImplPort() {
        return super.getPort(new QName("http://SOA.BizAgi/", "EntityManagerSOAImplPort"), EntityManagerSOAImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntityManagerSOAImpl
     */
    @WebEndpoint(name = "EntityManagerSOAImplPort")
    public EntityManagerSOAImpl getEntityManagerSOAImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SOA.BizAgi/", "EntityManagerSOAImplPort"), EntityManagerSOAImpl.class, features);
    }

}
