
package cidc.bizagi.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WorkflowEngineSOA", targetNamespace = "http://SOA.BizAgi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkflowEngineSOA {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActivitiesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetActivitiesAsString")
    @ResponseWrapper(localName = "getActivitiesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetActivitiesAsStringResponse")
    public String getActivitiesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignActivityAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.AssignActivityAsString")
    @ResponseWrapper(localName = "assignActivityAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.AssignActivityAsStringResponse")
    public String assignActivityAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEventsAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetEventsAsString")
    @ResponseWrapper(localName = "getEventsAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetEventsAsStringResponse")
    public String getEventsAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "abortCasesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.AbortCasesAsString")
    @ResponseWrapper(localName = "abortCasesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.AbortCasesAsStringResponse")
    public String abortCasesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoriesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCategoriesAsString")
    @ResponseWrapper(localName = "getCategoriesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCategoriesAsStringResponse")
    public String getCategoriesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssignationLogAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetAssignationLogAsString")
    @ResponseWrapper(localName = "getAssignationLogAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetAssignationLogAsStringResponse")
    public String getAssignationLogAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCasesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCasesAsString")
    @ResponseWrapper(localName = "getCasesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetCasesAsStringResponse")
    public String getCasesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setEventAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SetEventAsString")
    @ResponseWrapper(localName = "setEventAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SetEventAsStringResponse")
    public String setEventAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClosedActivitiesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetClosedActivitiesAsString")
    @ResponseWrapper(localName = "getClosedActivitiesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetClosedActivitiesAsStringResponse")
    public String getClosedActivitiesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "grantCaseAccessAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GrantCaseAccessAsString")
    @ResponseWrapper(localName = "grantCaseAccessAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GrantCaseAccessAsStringResponse")
    public String grantCaseAccessAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveActivityAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SaveActivityAsString")
    @ResponseWrapper(localName = "saveActivityAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SaveActivityAsStringResponse")
    public String saveActivityAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspendCasesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SuspendCasesAsString")
    @ResponseWrapper(localName = "suspendCasesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.SuspendCasesAsStringResponse")
    public String suspendCasesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWorkflowClassesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetWorkflowClassesAsString")
    @ResponseWrapper(localName = "getWorkflowClassesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.GetWorkflowClassesAsStringResponse")
    public String getWorkflowClassesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resumeCasesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.ResumeCasesAsString")
    @ResponseWrapper(localName = "resumeCasesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.ResumeCasesAsStringResponse")
    public String resumeCasesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCasesAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.CreateCasesAsString")
    @ResponseWrapper(localName = "createCasesAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.CreateCasesAsStringResponse")
    public String createCasesAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performActivityAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.PerformActivityAsString")
    @ResponseWrapper(localName = "performActivityAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.PerformActivityAsStringResponse")
    public String performActivityAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeCaseAccessAsString", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.RevokeCaseAccessAsString")
    @ResponseWrapper(localName = "revokeCaseAccessAsStringResponse", targetNamespace = "http://SOA.BizAgi/", className = "bizagi.soa.RevokeCaseAccessAsStringResponse")
    public String revokeCaseAccessAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
